repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.1
    hooks:
      - id: poetry-check      # Checks poetry config validity
      - id: poetry-lock       # Ensures poetry.lock is updated
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests via Poetry
        entry: |
          bash -c '
          set -e
          poetry run pytest tosk_bot/base/tests || exit_code=$?
          poetry run pytest tosk_bot/ext/ping/tests || exit_code=$?
          if [ -n "$exit_code" ]; then
            exit $exit_code
          fi
          '
        language: system
        pass_filenames: false
        always_run: false
        files: ^(tosk_bot/.*/service/.*\.py|tosk_bot/.*/tests/.*\.py)$
  - repo: https://github.com/psf/black
    rev: 25.9.0  # Use the latest stable Black version
    hooks:
      - id: black
        language_version: python3.14
