services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP port for Python services
      - "15672:15672"   # RabbitMQ management UI (optional)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  base-service:
    image: ${USERNAME}/tosk-bot-base:${TAG}
    build:
      context: .
      labels:
        - "org.opencontainers.image.title=${TITLE}"
        - "org.opencontainers.image.version=${VERSION}"
        - "org.opencontainers.image.description=${DESCRIPTION}"
        - "org.opencontainers.image.licenses=${LICENSE}"
        - "org.opencontainers.image.source=${SOURCE}"
        - "org.opencontainers.image.revision=${REVISION}"
        - "org.opencontainers.image.created=${CREATED}"
      dockerfile: tosk_bot/base/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      TOSK_BOT_BASE_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    restart: unless-stopped

  ping-service:
    image: ${USERNAME}/tosk-bot-ext-ping:${TAG}
    build:
      context: .
      labels:
        - "org.opencontainers.image.title=${TITLE}"
        - "org.opencontainers.image.version=${VERSION}"
        - "org.opencontainers.image.description=${DESCRIPTION}"
        - "org.opencontainers.image.licenses=${LICENSE}"
        - "org.opencontainers.image.source=${SOURCE}"
        - "org.opencontainers.image.revision=${REVISION}"
        - "org.opencontainers.image.created=${CREATED}"
      dockerfile: tosk_bot/ext/ping/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      TOSK_BOT_BASE_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    restart: unless-stopped
